# =============================================================================
#                  TCAM tables configuration list format
# -----------------------------------------------------------------------------
# tcamTableX      : config of Nth tcam table
# queryStrLen     : total length (in bits) of the input query string
# subStrLen       : total length (in bits) of each query sub string
# totalSubStr     : total number of query sub strings
#           queryStrLen = totalSubStr * subStrLen
# potMatchAddr    : total numbr of potential math addresses in TCAM table
# =============================================================================


tcamTable1:
    queryStrLen: 20
    subStrLen: 5
    totalSubStr: 4
    potMatchAddr: 8

tcamTable2:
    queryStrLen: 32
    subStrLen: 8
    totalSubStr: 4
    potMatchAddr: 8

tcamTable3:
    queryStrLen: 15
    subStrLen: 5
    totalSubStr: 3
    potMatchAddr: 8

tcamTable4:
    queryStrLen: 10
    subStrLen: 2
    totalSubStr: 5
    potMatchAddr: 16
